/**/riptide_gyro:
  ros__parameters:
    # configuration information
    gyro_port: /dev/ttyUSB0
    gyro_frame: talos/fog_link

    # calibration parameters
    # formula: z(x,y) = a + b*x + c*x*y + d*cos(f*x + g)
    a: 0.08252
    b: -25.49
    c: -0.001824
    d: 463.2
    f: 0.05289
    g: -1.571
    rate_norm_mean: -13879.06
    rate_norm_std: 1587500.0
    temp_norm_mean: 42.96093
    temp_norm_std: 4.295707

    variance: 0.0001

    #calibration limits
    cal_temp_limits: [37.57019, 51.303101]
