/**/riptide_gyro:
  ros__parameters:
    # configuration information
    gyro_port: /dev/ttyUSB0
    gyro_frame: talos/base_link

    # calibration parameters
    p00: 0.0006594
    p10: 0.9623
    p01: 4.29e-05
    p20: 0.0003649
    p11: 0.001806
    rate_norm_mean: 1192.0
    rate_norm_std: 1517000.0
    temp_norm_mean: 12140.0
    temp_norm_std: 558.6

    variance: 0.0001

    #calibration limits
    cal_temp_limits: [11000, 13500]
