# Sets the target for the mapping system
# If the object is set to null/None the mapping system will use the closest object
string target_object

# Locks the map so nothing will change
bool lock_map
---
