#request definition
geometry_msgs/PoseStamped[] path_points

---
#result definition
TrajPoint[] traj_points

uint8 error_code
string error_msg

uint8 NO_ERROR=0
uint8 BAD_WYPTS=1
uint8 MISSING_FRAME_ID=2