# Positions are in meters from back left foot. ENU convention
# Pose is xyzrpy with rpy in radians

# Point which represents robot position. Must be near center
base_link: [0.397, -0.205, 0.17]

# Vehicle mass properties
mass: 39.825 # kg
com: [0.397, -0.205, 0.17] # m
inertia: [1.32, 2.84, 3.65] # kg*m^2

# Vehicle bouyancy properties
volume: 0.041411663076 # m^3
cob: [0.427166374353, -0.20500255449, 0.206254579485]

# Controller parameters
controller:
  linear:
    # linear damping coeficients
    damping:
      # linear: [-51, -50, -50.0]
      # quadratic: [-23, -460.0, -460.0]
      linear: [0.0, 0.0, 0.0]
      quadratic: [0.0, 0.0, 0.0]

    # physical maximums for each linear axis
    max:
      velocity: [.45, .2, .2]
      acceleration: [1.0, 1.0, 1.0]

    # linear controller proportional gains
    p_gains:
      position: [1, 1, 1]
      velocity: [4, 4, 4]

  angular:
    # angular damping coeficients
    damping:
      # linear: [-2, -4.5, -2.5]
      # quadratic: [-6, -12, -12]
      linear: [0.0, 0.0, 0.0]
      quadratic: [0.0, 0.0, 0.0]

    # physical maximums for each rotational axis
    max:
      velocity: [.5, .5, 1]
      acceleration: [2.0, 2.0, 2.0]

    # Angular controller proportional gains
    p_gains:
      position: [300, 300, 300]
      velocity: [10, 10, 10]

dvl:
  topic: dvl
  rate: 8 # Hz
  sigma: 0.001 # Stdev in m/s. Used by gazebo
  pose: [0.3302, 0.005, 0.1289, 0, 0, -2.35619]

depth:
  topic: depth/pressure
  rate: 20 # Hz
  sigma: 0.003 # Stdev in m. Used by gazebo
  pose: [0.43815, -0.1397, 0.13335, 0, 0, 0] # TODO WRONG!

imu:
  topic: imu/imu/data
  # Noise modeling is weird and is hard coded in urdf with some numbers.
  # TODO: Model noise
  rate: 100 #Hz
  pose: [0.69215, -0.19685, 0.33, 0, 0, 0] # TODO WRONG!

cameras: [
  {
    type: stereo, 
    name: stereo,
    model: zed2,
    baseline: 0.12, # m. Distance between cameras (manually measured) 
    pose: [-0.242, 0.283, -0.066, 0, 0, 0] # TODO WRONG!
  }
]

thruster: # TODO WRONG!
  rotor_constant: 0.01 # Not sure units. If too low bot shakes in sim
  max_force: 30 # Newtons. Thrusters draw about 8A here
  MIN_THRUST: 0.2
  STARTUP_THRUST: 1.5
  SU_THRUST:
    POS_SLOPE: 22.500000
    POS_YINT: 1520
    NEG_SLOPE: 28.600000
    NEG_YINT: 1477
  THRUST:
    POS_SLOPE: 6.66
    POS_YINT: 1552
    NEG_SLOPE: 8.54
    NEG_YINT: 1444


thrusters: [
  {
    name: "HSA",
    type: 1,
    pose: [0.08255, -0.3683, 0.161925, 0.0, -1.57079, 0.0]
  },
  {
    name: "HSF",
    type: 1,
    pose: [0.7747, -0.3683, 0.161925, 0.0, -1.57079, 0.0]
  },
  {
    name: "VSF",
    type: 0,
    pose: [0.8255, -0.48895, 0.257175, 0.0, 0.0, -2.35619]
  },
  {
    name: "VSA",
    type: 0,
    pose: [0.03175, -0.48895, 0.257175, 0.0, 0.0, -0.78540]
  },
  {
    name: "HPF",
    type: 1,
    pose: [0.7747, 0, 0.161925, 0.0, -1.57079, 0.0] 
  },
  {
    name: "HPA",
    type: 1,
    pose: [0.08255, 0, 0.161925, 0.0, -1.57079, 0.0] 
  },
  {
    name: "VPF",
    type: 0,
    pose: [0.8255, 0.12065, 0.257175, 0.0, 0.0, 2.35619]
  },
  {
    name: "VPA",
    type: 0,
    pose: [0.03175, 0.12065, 0.257175, 0.0, 0.0, 0.78540]
  }
]