# Positions are in meters from back left foot. ENU convention
# Pose is xyzrpy with rpy in radians

# Point which represents robot position. Must be near center
base_link: [-0.3556, 0.0, 0.0]

# Vehicle mass properties
mass: 31.437 #kg
com: [-0.360, 0.0, 0.121]
inertia: [1.32, 2.84, 3.65] # kg*m^2

# Vehicle bouyancy properties
volume: 0.037655 # m^3
cob: [-0.340, 0.0, 0.121]

# Controller parameters
controller:
  linear:
    # linear damping coeficients
    damping:
      linear: [-51.0, -50.0, -50.0]
      quadratic: [-23.0, -460.0, -460.0]

    # physical maximums for each linear axis
    max:
      velocity: [.45, .4, .2]
      acceleration: [1.0, 1.0, 1.0]

    # linear controller proportional gains
    p_gains:
      position: [1.0, 1.0, 1.0]
      velocity: [4.0, 4.0, 4.0]

  angular:
    # angular damping coeficients
    damping:
      linear: [-2.0, -4.5, -2.5]
      quadratic: [-6.0, -12.0, -12.0]

    # physical maximums for each rotational axis
    max:
      velocity: [0.5, 0.5, 1.0]
      acceleration: [2.0, 2.0, 2.0]

    # Angular controller proportional gains
    p_gains:
      position: [300.0, 300.0, 300.0]
      velocity: [10.0, 10.0, 10.0]

dvl:
  # topic: dvl
  rate: 8 # Hz
  sigma: 0.001 # Stdev in m/s. Used by gazebo
  pose: [-0.205, 0.175, -0.062, 0, 0, -2.35619]

depth:
  # topic: depth/pressure
  rate: 20 # Hz
  sigma: 0.003 # Stdev in m. Used by gazebo
  pose: [-0.40, 0, 0.0361, 0, 0, 0] # TODO WRONG!

imu:
  rate: 100 #Hz
  pose: [-0.049, 0.0, 0.221, 3.1415, 0, 0]

claw:
  pose: [-0.35, 0.82, -0.066, 0, 0, 1.507]

torpedos: 
  pose: [-0.1143, 0.7112, 0.03175, 0, 0, 0]

droppers:
  pose: [-0.35, 0, 0.05, 0, 0, 0]

cameras: [
  {
    type: stereo, 
    name: zed2i,
    model: zed2,
    baseline: 0.12, # m. Distance between cameras (manually measured) 
    pose: [-0.0254, 0, 0.168, 0, 0, 0]
  }
]

thruster: # TODO WRONG!
  rotor_constant: 0.01 # Not sure units. If too low bot shakes in sim
  max_force: 22 # Newtons. Thrusters draw about 8A here
  MIN_THRUST: 0.2
  STARTUP_THRUST: 1.5
  SU_THRUST: #Start Up Thrust
    POS_SLOPE: 59.94
    POS_YINT: -13.32
    NEG_SLOPE: 76.19
    NEG_YINT: 5.328
  THRUST:
    POS_SLOPE: 17.74
    POS_YINT: 71.928
    NEG_SLOPE: 22.75
    NEG_YINT: -82.584

# Note: thruster type means the attack direction of the thruster. This means that the type of the thruster should match which way the thruster is expected to spin for the thruster test
# Thruster naming convention:
#  - first letter:  direction  (Heave/Vector)
#  - second letter:            (Port / Starboard)
#  - third letter:             (Port/Starboard)
thrusters: [
  {
    name: "VPF", #1
    type: 0,
    pose: [0.078, 0.303, 0.157, 0.0, 0.0, 2.35619]
  },
  {
    name: "VPA", #2
    type: 0,
    pose: [-0.719, 0.303, 0.157, 0.0, 0.0, 0.78540]
  },
  {
    name: "HPF", #3
    type: 0,
    pose: [0.029, 0.189, 0.040, 0.0, -1.57079, 0.0] 
  },
  {
    name: "HPA", #4
    type: 1,
    pose: [-0.670, 0.189, 0.040, 0.0, -1.57079, 0.0] 
  },
  {
    name: "HSF", #5
    type: 1,
    pose: [0.029, -0.189, 0.040, 0.0, -1.57079, 0.0]
  },
  {
    name: "HSA", #6
    type: 1,
    pose: [-0.670, -0.189, 0.040, 0.0, -1.57079, 0.0]
  },
  {
    name: "VSF", #7
    type: 1,
    pose: [0.078, -0.303, 0.157, 0.0, 0.0, -2.35619]
  },
  {
    name: "VSA", #8
    type: 0,
    pose: [-0.719, -0.303, 0.157, 0.0, 0.0, -0.78540]
  } 
]
