#super secret yaml file for all things Nathan sim

#The Vehicle should never load this file!!! 
#If you are loading things from here onto the vehicle you are doing something wrong!
#You should likely look at vehicle.yaml located in this directory
#This file is made to serpate out parameters that are used only in the simulator, like ground truths.
#Some of these may be depricated parameters from the vehicle! Even if it looks like a vehicle parameter, its not one!

vehicle_properties:
  talos:
    base_wrench: [0.0, 0.0, -4.9, -0.95, 2.1, 0.0]
    cod: [-0.148, 0.040, -0.055]
    inertia3x3: [1.6315, -0.0599, -0.0330, # Ixx Ixy Ixz
                -0.0599, 0.7341, 0.0427,  # Iyx Iyy Iyz
                -0.0330, 0.0427, 1.6332]  # Izx Izy Izz kg*m^

    #center of mass discrepancy      
    dcom: [0.01, 0.0, 0.0]
                
    # drag = (k1 + k2 * abs(v) + k3 * exp(abs(v) / k4) )* sign(v)
    damping: [-38.7588,  -28.1146,   37.3211,    0.5034, #x
              -7.4651,   17.7641,    7.0013,    0.3067, #y
              -7.0964,   27.6349,    6.9723,    0.3827, #z
              -4.6881,    5.2662,    6.2630,    1.2739, #r
              -18.1269,   -3.1893,   17.3711,    2.0801, #p
              -20.4148,   -8.2547,   20.2604,    1.6177] #yaw

    thruster_max_force: 28.0

    #sim discrepency - allows to test control when feed forward is not perfect
    sim_discrepancy: [0.0, 1.0, -0.5, 0.1, -0.05, 0.0]

    env_force: [0.0, 2.0, 0.0]

  liltank: #TODO: measure or estimate all liltank parameters
    cob: [0.0, 0.0, 0.15]
    cod: [0.0, 0.0, -0.055]
    inertia3x3: [1.6315, -0.0599, -0.0330, # Ixx Ixy Ixz
                -0.0599, 0.7341, 0.0427,  # Iyx Iyy Iyz
                -0.0330, 0.0427, 1.6332]  # Izx Izy Izz kg*m^2

    # drag = (k1 + k2 * abs(v) + k3 * exp(abs(v) / k4) )* sign(v)
    damping: [-38.7588,  -28.1146,   37.3211,    0.5034, #x
              -7.4651,   17.7641,    7.0013,    0.3067, #y
              -7.0964,   27.6349,    6.9723,    0.3827, #z
              -4.6881,    5.2662,    6.2630,    1.2739, #r
              -18.1269,   -3.1893,   17.3711,    2.0801, #p
              -20.4148,   -8.2547,   20.2604,    1.6177] #yaw

    thruster_max_force: 28.0

    #sim discrepency - allows to test control when feed forward is not perfect
    sim_discrepancy: [0.0, 0.0, 0.0, 0.0, 0.0, 0.0]


claw:
  fake_objects: #I've arbilitrarilly set these properties - measure at some point
    coral:
      net_buoyancy: 2.0 #positive =  positively bouyant, negative = negatively buoyant
      com: [.1, 0.0, -0.1] # the "origin" of the object is where the end affector grips the object      
    tubeworm:
      net_buoyancy: 1.0 #positive =  positively bouyant, negative = negatively buoyant
      com: [.1, 0.0, -0.1] # the "origin" of the object is where the end affector grips the object
    nautilus:
      net_buoyancy: 2.0 #positive =  positively bouyant, negative = negatively buoyant
      com: [.4, 0.0, -0.0] # the "origin" of the object is where the end affector grips the object


acoustics:
    #fake pinger location for simulaation
  fake_pinger:
    pose: [3.0, 2.0, -1.0, 0.0, 0.0, 0.0]

preferences:
  sync_odom: true
