# Positions are in meters from back left foot. ENU convention
# Pose is xyzrpy with rpy in radians

# Point which represents robot position. Must be near center
base_link: [-0.14, 0.03, -0.09]

# Vehicle mass properties
mass: 31.998
com: [-0.148, 0.040, -0.071]
inertia: [1.493, 0.549, 1.399] # kg*m^2

# Controller parameters
controller:
  feed_forward:
    base_wrench: [0.3, 0.0, -6.0, 0.275, 0.050, -0.085]
  linear:
    # linear damping coeficients
    damping:
      # linear: [-17.0, -17.0, -35.0]
      # quadratic: [-180.0, -180.0, -460.0]
      linear: [0.0, 0.0, 0.0]
      quadratic: [0.0, 0.0, 0.0]

    # physical maximums for each linear axis
    max:
      velocity: [.45, .4, .2]
      acceleration: [1.0, 1.0, 1.0]

    # linear controller proportional gains
    p_gains:
      # position: [1.2, 1.2, 0.9]
      # velocity: [7.5, 15.0, 22.0]
      position: [0.8, 0.8, 0.7]
      velocity: [7.0, 14.5, 21.0]

  angular:
    # angular damping coeficients
    damping:
      # linear: [-2.0, -4.5, -2.5]
      # quadratic: [-6.0, -12.0, -12.0]
      linear: [0.0, 0.0, 0.0]
      quadratic: [0.0, 0.0, 0.0]

    # physical maximums for each rotational axis
    max:
      velocity: [2.0, 2.0, 2.0]
      acceleration: [8.0, 8.0, 8.0]

    # Angular controller proportional gains
    p_gains:
      position: [250.0, 450.0, 100.0]
      velocity: [4.0, 2.2, 8.0]

dvl:
  # topic: dvl
  rate: 8 # Hz
  sigma: 0.001 # Stdev in m/s. Used by gazebo
  pose: [-0.119, 0.034, -0.250, 0, 0, -0.7853981]

depth:
  # topic: depth/pressure
  rate: 20 # Hz
  sigma: 0.003 # Stdev in m. Used by gazebo
  pose: [ -0.305, -0.125, 0.045, 0.0, 0.0, 0.0]

imu:
  # topic: /imu/imu/data
  rate: 100 #Hz
  pose: [-0.122, -0.147, 0.025, 3.141, 0.0, 3.141]

poker:
  pose: [0.2286, 0.0127, -0.17145, 0, 0, 0]

torpedos: 
  pose: [0.0542, -0.0929, -0.1756, 0.0, 0.0, 0.0]

droppers:
  pose: [-0.35, 0, 0.05, 0, 0, 0]

cameras: [
  {
    type: stereo, 
    name: zed2i,
    model: zed2,
    baseline: 0.12, # m. Distance between cameras (manually measured) 
    pose: [-0.060, -0.088, 0.0, 0, 0, 0]
  }
]

#this is for the newly developed solver
thruster_solver:
  
  #default weights for the thruster solver
  default_weight: 1.0

  #power for lower heave thrusters for low downdraft mode
  low_downdraft_weight: 3.0

  #weight for disabled thrusters
  disable_weight: 2000.0

  #weight for surfaced thruster
  surfaced_weight: 4.0

  #the system limit for total thrust (N)
  system_thrust_limit: 73

  #the limit for an individual thruster
  individual_thrust_limit: 24

  force_to_rpm_coefficents: [-475.886186, 32.327429, -324.744664, 1443.832105, 257.460623, 42.948545, -24.402056, -986.338071]
  #Format: 4 times positive curve then 4 times negative curve
  # 1 * 1
  # 2 * x
  # 3 * tanh(x)
  # 4-* x^(1/4)

#params for the newly developed overseer
controller_overseer:

  #the height above water at which to kill the thrusters (m)
  thruster_kill_plane: 0.1

# Note: thruster type means the attack direction of the thruster. This means that the type of the thruster should match which way the thruster is expected to spin for the thruster test
# Thruster naming convention:
#  - first letter:  direction         (Heave/Vector)
#  - second letter: vertical position (Upper/Lower)
#  - third letter:  lateral position  (Port/Starboard)
thrusters: [
  {
    name: "VUS", #thruster 0
    type: 1,
    pose: [-0.134, -0.369, 0.242, 0.0, 0.0, 0.0]
  },
  {
    name: "VUP", #thruster 1
    type: 0,
    pose: [-0.134, 0.438, 0.242, 0.0, 0.0, 0.0]
  },
  {
    name: "HUS", #thruster 2
    type: 0,
    pose: [-0.140, -0.260, 0.141, 0.0, -0.785, 1.571]
  },
  {
    name: "HUP", #thruster 3
    type: 1,
    pose: [-0.140, 0.328, 0.141, 0.0, -0.785, -1.571] 
  },
  {
    name: "HLS", #thruster 4
    type: 1,
    pose: [-0.140, -0.260, -0.141, 0.0, 0.785, 1.571]
  },
  {
    name: "HLP", #thruster 5
    type: 0,
    pose: [-0.140, 0.328, -0.141, 0.0, 0.785, -1.571]
  },
  {
    name: "VLS", #thruster 7
    type: 0,
    pose: [-0.134, -0.372, -0.244, 0.0, 0.0, 0.0]
  },
  {
    name: "VLP", #thruster 8
    type: 1,
    pose: [-0.134, 0.440, -0.244, 0.0, 0.0, 0.0]
  }
]