/**:
  ros__parameters:
    general:
      camera_model: "zedxm"
      serial_number: 51491740
      optional_opencv_calibration_file: "/home/ros/zed_cals/zed_dfc_calibration2.yaml"
    # svo:
    #   svo_path: "" # Must be absolute path
    debug:
      debug_common: false
      debug_point_cloud: false
