/**:
  ros__parameters:
    general:
      camera_model: "zed2i"
      serial_number: 38888324
      optional_opencv_calibration_file: "/home/ros/zed_cals/ffc_calibration3.yaml"
    # svo:
    #   svo_path: "" # Must be absolute path
    debug:
      debug_common: false
      debug_point_cloud: false
