/**:
  ros__parameters:
    general:
      camera_model: "zed2i"
      serial_number: 38888324
      grab_resolution: 'HD2K' # For zedx use HD1200, for zed2i use HD2K
      optional_opencv_calibration_file: "/home/ros/zed_cals/ffc_calibration3.yaml"
      pub_resolution: "CUSTOM" # The resolution used for image and depth map publishing. 'NATIVE' to use the same `general.grab_resolution` - `CUSTOM` to apply the `general.pub_downscale_factor` downscale factory to reduce bandwidth in transmission
      pub_downscale_factor: 2.0 # rescale factor used to rescale image before publishing when 'pub_resolution' is 'CUSTOM'
      pub_frame_rate: 30.0
    # svo:
    #   svo_path: "" # Must be absolute path
    debug:
      debug_common: false
      debug_point_cloud: false
      debug_video_depth: false
