---
/**:
    ros__parameters:
        ffmpeg_image_transport:
          # bit_rate: 4194304 # Default: 8242880
          delay: '0' # default is 4 frames for parallel processing. 0 is lowest latency
          encoding: 'hevc_nvenc' # Only ever tested: libx264, h264_nvenc, h264, hevc_nvenc, h264_vaapi. If you have an Nvidia card it most likely supports hevc_nvenc. This will dramatically reduce the CPU load compare to libx264 (the default). You can list all available codecs with ffmpeg -codecs. In the relevant row, look for what it says under (encoders).
          gop_size: 10 # The number of frames inbetween keyframes. Default is 15. The larger this number the more latency you will have, but also the more efficient the transmission becomes.
          # measure_performance: false # Enable performance analysis
          # performance_interval: 100 # number of frames between perf printouts
          # pixel_format: ''
          # preset: '' # 'll','ultrafast','superfast','veryfast','faster','fast','medium','slow','slower','veryslow' -> https://trac.ffmpeg.org/wiki/Encode/H.264#Preset
          # profile: '' # 'baseline','main' -> https://trac.ffmpeg.org/wiki/Encode/H.264#Tune
          # qmax: 0 # max allowed quantization. The lower the better quality
          # tune: '' # 'film','animation','grain','stillimage','fastdecode','zerolatency'


        zed_node.depth.depth_registered.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.left.image_rect_color.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.left_gray.image_rect_gray.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.left_raw.image_raw_color.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.left_raw_gray.image_raw_gray.enable_pub_plugins:
          - "image_transport/raw"
        # zed_node.point_cloud.cloud_registered.enable_pub_plugins:
        #   - "image_transport/raw"
        zed_node.rgb.image_rect_color.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.rgb_gray.image_rect_gray.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.rgb_raw.image_raw_color.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.rgb_raw_gray.image_raw_gray.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.right.image_rect_color.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.right_gray.image_rect_gray.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.right_raw.image_raw_color.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.right_raw_gray.image_raw_gray.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.stereo.image_rect_color.enable_pub_plugins:
          - "image_transport/raw"
        zed_node.stereo_raw.image_raw_color.enable_pub_plugins:
          - "image_transport/raw"