# Voltage of the port battery rail
float32 port_voltage

# Voltage of the starboard battery rail
float32 stbd_voltage

# Voltage of the V+ rail after the battery balancer
float32 balanced_voltage

# Voltage of the 12V rail (really 15V)
float32 twelve_volt_voltage

# Voltage of the 5V rail
float32 five_volt_voltage

# Voltage of the 3V3 rail
float32 three_volt_voltage

# Is the stbd battery powering the robot
bool stbd_powering

# Is the port battery powering the robot
bool port_powering
